// SynapseAI hybrid engine: offline curriculum generation + optional
// Google Gemini REST calls when the user configures an API key.

import { KNOWLEDGE_BASE, GENERAL_CURRICULUM, PERSONAS } from './knowledgeBase';
import { uid } from '../hooks/useLocalStorage';

const shuffle = (arr) => [...arr].sort(() => Math.random() - 0.5);

const PERSONA_SYS_MAP = Object.fromEntries(PERSONAS.map((p) => [p.id, p.sys]));

export function resolveCurriculum(specialty) {
  if (!specialty || specialty === 'general' || !KNOWLEDGE_BASE[specialty]) return GENERAL_CURRICULUM;
  return KNOWLEDGE_BASE[specialty];
}

export function makeTest({ specialty, topic, count = 3, title }) {
  const kb = resolveCurriculum(specialty);
  const pool = kb.vignettes.filter((v) => !topic || v.topic === topic);
  const base = (pool.length ? pool : kb.vignettes);
  const picked = shuffle(base).slice(0, Math.min(count, base.length)) || base.slice(0, 3);
  const fallback = [];
  for (let i = picked.length; i < Math.min(count, base.length); i++) {
    fallback.push(base[i]);
  }
  const questions = shuffle([...picked, ...fallback]).map((v) => ({
    id: uid(),
    text: v.stem,
    options: v.options,
    correctIndex: v.correct,
    explanation: v.explanation,
    source: 'synapse-ai',
    topic: v.topic,
  }));
  if (!questions.length) {
    return {
      id: uid(),
      title: title || `SynapseAI ${kb.label}`,
      subjectId: '',
      topicId: '',
      questions: [{
        id: uid(),
        text: `Generate a clinical vignette on ${topic || kb.label}.`,
        options: ['Option A', 'Option B', 'Option C', 'Option D'],
        correctIndex: 0,
        explanation: 'Connect Google Gemini in Settings for richer online generation; offline curriculum did not match this topic.',
        source: 'synapse-ai',
      }],
    };
  }
  return {
    id: uid(),
    title: title || `SynapseAI ${kb.label}${topic ? ` — ${topic}` : ''}`,
    subjectId: '',
    topicId: '',
    questions,
    createdAt: new Date().toISOString(),
    source: 'synapse-ai',
  };
}

export function makeNotes({ specialty, topic, persona }) {
  const kb = resolveCurriculum(specialty);
  const nm = kb.notes;
  const personaLens =
    persona === 'board'
      ? '\n[Board-exam lens: train your trap radar — underline the classic wrong-path finding in each section.]'
      : persona === 'attending'
      ? '\n[Clinical lens: read this as a handoff — what would you act on tonight?]'
      : '';
  const block = (title, items) =>
    `## ${title}\n${Array.isArray(items) ? items.map((i, n) => `${n + 1}. ${i}`).join('\n') : items}`;
  const out = [
    `# ${nm.title}${topic ? ` — ${topic}` : ''}`,
    `## Pathophysiology\n${nm.pathophysiology}`,
    block('Diagnostic Benchmarks', nm.diagnostics),
    block('Pharmacotherapy', nm.pharmacotherapy),
    `## Traps & Easy-to-Miss\n${nm.traps.map((t) => `- ${t}`).join('\n')}`,
    personaLens,
    `\n_Generated by SynapseAI offline curriculum · ${kb.label}${persona ? ` · ${persona}` : ''}_`,
  ].join('\n\n');
  return out;
}

export function makeFlashcards({ specialty, topic, count = 6, persona }) {
  const kb = resolveCurriculum(specialty);
  const pool = kb.flash.filter((f) => !topic || f.topic === topic);
  const base = pool.length ? pool : kb.flash;
  const picked = shuffle(base).slice(0, count);
  const hint =
    persona === 'board'
      ? ' (high-yield: will appear in the test exactly like this — recognize the trap)'
      : persona === 'attending'
      ? ' (reason from physiology first, then recall the fact)'
      : '';
  return picked.map((f) => ({
    id: uid(),
    front: f.front + hint,
    back: f.back,
    subjectId: '',
    topicId: '',
    type: 'custom',
    source: 'synapse-ai',
    createdAt: new Date().toISOString(),
  }));
}

const TRAP_RULES = [
  { rx: /contraindicat|should not|do not|avoid|never/i, trap: 'Contraindication trap — you picked an agent that is directed at the wrong mechanism (or outright forbidden in this physiology).' },
  { rx: /first.?line|next step|most appropriate|initial|immediately|within/i, trap: 'Priority/sequence trap — the question asked for the FIRST action, not the best long-term treatment.' },
  { rx: /classic|highest|most common|typical/i, trap: 'Prototype trap — you reached for the general category instead of the classic, pathognomonic presentation.' },
  { rx: /time|window|minutes|hours|delay/i, trap: 'Timing trap — reperfusion/review windows are graded literally; seconds-to-minutes matter.' },
  { rx: /pearl|mnemonic|mnemonic/i, trap: 'Recall trap — the answer lives in a mnemonic pairing you did not surface under pressure.' },
];

export function diagnoseMistakes(missed) {
  const analysis = (missed || []).map((q, _i) => {
    const t = TRAP_RULES.find((r) => r.rx.test(q.explanation || ''));
    return {
      q: q.text,
      trap: t ? t.trap : 'Discrimination trap — two options differed by one discriminating feature; re-derive the decision rule, do not partially recall it.',
      fix: q.explanation,
    };
  });
  const themes = analysis.reduce((acc, a) => acc.add(a.trap.split(' — ')[0]), new Set());
  const header =
    missed.length === 0
      ? '# Mistake Diagnosis\nNo missed questions supplied — run a test with incorrect answers or paste them below.'
      : `# Mistake Diagnosis — ${missed.length} question${missed.length > 1 ? 's' : ''} missed\n\n## Cognitive traps detected\n${themes.size ? [...themes].map((t) => `- ${t}`).join('\n') : '- Review below'}\n\n## Question-by-question\n${analysis
          .map(
            (a, i) =>
              `### Miss ${i + 1}\n**Question:** ${a.q}\n**Trap:** ${a.trap}\n**Correction:** ${a.fix}`
          )
          .join('\n\n')}\n\n## 3-Point Remediation Plan\n1. **Re-anchor:** rebuild the decision rule from physiology — write the normal pathway first, then where the pathology breaks it.\n2. **Drill the discriminator:** re-answer each missed item tomorrow (Leitner box 1) and explain your choice aloud.\n3. **Danger-track:** add a "one-liner" flashcard for each missed item — the correct answer + ONE reason the distractor tempted you.`;
  return header;
}

function systemFor({ persona, specialty, topic }) {
  const p = PERSONA_SYS_MAP[persona] || 'You are a rigorous clinical educator. Be precise, kind, and evidence-based.';
  return `${p}\nTeaching context: specialty="${specialty || 'general'}"${topic ? `, topic="${topic}"` : ''}.`;
}

export async function askCopilot({ query, specialty, topic, persona, api, model }) {
  const system = systemFor({ persona, specialty, topic });
  if (api?.key) {
    return askGemini({ system, query, api, model });
  }
  return offlineAnswer(query, { specialty, topic });
}

async function askGemini({ system, query, api, model }) {
  const m = model || 'gemini-2.0-flash';
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${m}:generateContent?key=${encodeURIComponent(api.key)}`;
  const res = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      systemInstruction: { parts: [{ text: system }] },
      contents: [{ role: 'user', parts: [{ text: query }] }],
      generationConfig: { temperature: 0.4, maxOutputTokens: 1200 },
    }),
  });
  if (!res.ok) {
    const err = await res.text().catch(() => '');
    throw new Error(`Gemini error ${res.status}: ${err.slice(0, 200)}`);
  }
  const data = await res.json();
  const text = data?.candidates?.[0]?.content?.parts?.map((p) => p.text || '').join('\n') || '';
  return { text, online: true };
}

function offlineAnswer(query, { specialty, topic }) {
  const q = query.toLowerCase();
  const hits = [];
  const kb = resolveCurriculum(specialty);
  const sections = [];
  if (kb.notes) sections.push(kb.notes);
  // search flashcards + vignettes for keywords
  const flashHits = (kb.flash || []).filter((f) =>
    q.split(/\s+/).some((w) => w.length > 3 && `${f.front} ${f.back}`.toLowerCase().includes(w))
  );
  const vigns = (kb.vignettes || []).filter((v) =>
    q.split(/\s+/).some((w) => w.length > 3 && v.stem.toLowerCase().includes(w) && !v.explanation.includes('first-line'))
  );
  const topicHits = (kb.topics || []).filter((t) => q.includes(t.toLowerCase()));
  for (const s of sections) {
    if (s.pathophysiology) hits.push(`## Pathophysiology\n${s.pathophysiology}`);
    if (Array.isArray(s.pharmacotherapy)) hits.push(`## Pharmacotherapy\n${s.pharmacotherapy.map((x, i) => `${i + 1}. ${x}`).join('\n')}`);
    if (Array.isArray(s.traps)) hits.push(`## Traps\n${s.traps.join('\n')}`);
  }
  flashHits.slice(0, 3).forEach((f) => hits.push(`## Flashcard: ${f.front}\n${f.back}`));
  if (!hits.length && vigns.length) {
    const v = vigns[0];
    hits.push(`## Practice vignette\n${v.stem}\n\n**Answer:** ${v.options[v.correct]}\n**Why:** ${v.explanation}`);
  }
  if (!hits.length) {
    let lead = '';
    if (topicHits.length) lead = `\nCovering ${specialty || 'general'} → topics: ${topicHits.join(', ')}.`;
    hits.push(
      `# Offline curriculum search\n${lead}\nI didn't find a direct match in the offline knowledge base. Here is the strongest adjacent content:\n\n` +
        `- **Ask sharper:** add a keyword like "${
          specialty && specialty !== 'general' ? resolveCurriculum(specialty).topics[0] : 'heart failure or stroke'
        }".\n- **Go deeper:** connect Google Gemini in **Settings** for web-scale generation on this specific question.\n- **Ground truth:** verify management questions against your institution's latest guidelines.`
    );
  }
  const text = [`# SynapseAI · ${specialty !== 'general' ? resolveCurriculum(specialty).label + (topic ? ` · ${topic}` : '') : 'General'}`, ...hits].join('\n\n');
  return { text, online: false };
}

export { SPECIALTIES } from './knowledgeBase';